# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Define a name for controllers that we plan to use
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    my_controller2:
      type: my_controller2/MyController2

# Properties of the custom controler and definition of joints to use
my_controller2:
  ros__parameters:
    joints:
      - arm_joint1
      - arm_joint2
    interface_name: position

