controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    my_controller:
      type: my_controller/MyController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

my_controller:
  ros__parameters:
    joints:
      - arm_joint1
      - arm_joint2
    interface_name: position


# joint_state_broadcaster:
#   ros__parameters:
