# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Define a name for controllers that we plan to use
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    my_controller:
      type: my_controller/MyController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
# Properties of the custom controler and definition of joints to use
my_controller:
  ros__parameters:
    joints:
      - arm_joint1
      - arm_joint2
    interface_name: effort
    test_parameter:
      sub_parameter1: 1
      sub_parameter2: 2

forward_position_controller:
  ros__parameters:
    joints:
      - arm_joint

forward_velocity_controller:
  ros__parameters:
    joints:
      - arm_joint
